export const mainUser = [
  {
    id: 1,
    name: "Эм, виртуальный помощник",
    message: "Во тьме ночной при свете дня, тут сообщение пишу я",
    img: "https://via.placeholder.com/500x500?text=Admin",
    date: "24 Апр, 15:50",
  },
];

export const messages = [
  {
    id: 1,
    name: "Константин Михалков",
    message: "Я ответственно заявляю, что в верстке есть большие",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 2,
    name: "Зинедин Зидан",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "Тренер",

  },
  {
    id: 3,
    name: "Владимир Путин",
    message: "Предсознательное стабильно. Рефлексия вызывает стимул. Эскапизм осознаёт импульс. ",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "30 Окт 15:20",
    position: "Президент",
  },
  {
    id: 4,
    name: "Психоз изменяем",
    message: "Мышление, например, однородно иллюстрирует стимул.",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 5,
    name: "Батька",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "Президент",
  },
  {
    id: 6,
    name: "Маргарита",
    message: "Психоз изменяем. Конформизм понимает психоз.",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 7,
    name: "Никита фролков",
    message: "Спасибо, оплатили!",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 8,
    name: "Михаэль Шумахер",
    message: "Мышление, например, однородно иллюстрирует стимул.",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "Водитель",
  },
  {
    id: 9,
    name: "Филипп Лам",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "Футболист",
  },
  {
    id: 10,
    name: "Френсис",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 11,
    name: "Френсис",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 12,
    name: "Филипп Лам",
    message: "Конфликтный гештальт: бессознательное или восприятие?",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "Футболист",
  },  {
    id: 13,
    name: "Маргарита",
    message: "Психоз изменяем. Конформизм понимает психоз.",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
  {
    id: 14,
    name: "Никита фролков",
    message: "Спасибо, оплатили!",
    img: "https://via.placeholder.com/500x500?text=User",
    date: "24 Апр 15:20",
    position: "",
  },
];
